module.exports = {
    ascii: 'string',
    bigint: 'number',
    blob: 'string',
    boolean: 'boolean',
    counter: 'number',
    decimal: 'number',
    double: 'number',
    float: 'number',
    int: 'number',
    text: 'string',
    timestamp: 'string',
    uuid: 'string',
    varchar: 'string',
    varint: 'number',
    timeuuid: 'string',
    inet: 'string',
    date: 'string',
    time: 'string',
    smallint: 'number',
    tinyint: 'number',
    duration: 'string',
    list: 'array',
    map: 'object',
    set: 'array',
    udt: 'string',
    tuple: 'array',
};
